name: Zeno
favicon: null
layout_spectrum: 0.3705047422554344
typography_spectrum: 0.22234971798025072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8166859403718263
  lightness: 0.8179390598088503
  saturation: 0.540960380807519
  rhythmicContrast: 0.6362854838371277
purpose: []
